# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/www'
                cache_prefix: 'media/cache'

    loaders:
        default:
            filesystem:
                data_root: '%kernel.project_dir%/www'

    driver: "gd"
    cache: default
    filter_sets:
        cache: ~

        # the name of the "filter set"
        my_thumb:
            # adjust the image quality to 75%
            quality: 75
            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [400, 240], mode: outbound }
        
        my_ratio_down_scale_filter:
            filters:

                # use and setup the "scale" filter
                scale:

                    # given 1920x1600px -> output 960x800px (relative down-scale)
                    to: 0.5