vich_uploader:
    db_driver: orm

    mappings:
        files:
            uri_prefix: /files
            upload_destination: '%kernel.project_dir%/www/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
        ronds:
            uri_prefix: /ronds
            upload_destination: '%kernel.project_dir%/www/japon/elements_graphiques/ronds/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


